app:
  base-url-github: "https://api.github.com"
  base-url-stackoverflow: "https://api.stackexchange.com"

  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper
  liquibase:
    change-log: ../../../../migrations/master.xml
    enabled: false
  datasource:
    driver_class_name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

base-url-bot: "http://localhost:8090"

