app:
  base-url-github: "https://api.github.com"
  base-url-stackoverflow: "https://api.stackexchange.com"
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
