app:
  telegram-token: 6378714764:AAE3fqaly7DTcPcP_NegirJ-UQeK2CeksJg

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

base-url-scrapper: "https://localhost:8090"
